import { defineStore } from "pinia";

export const useStoreSpavaceSobe = defineStore("spavaceSobe", {
  state: () => ({
    // ambijenti
    spavaceSobe: [
      {
        proizvodjac: "jela",
        img: "avis02",
        naziv: "avis",
        favorite: false,
        images: [
          "/images/ambijenti/spavace_sobe/jela/avis/avis01.webp",
          "/images/ambijenti/spavace_sobe/jela/avis/avis02.webp",
          "/images/ambijenti/spavace_sobe/jela/avis/avis03.webp",
          "/images/ambijenti/spavace_sobe/jela/avis/avis04.webp",
        ],
      },
      {
        proizvodjac: "jela",
        img: "invictus01",
        naziv: "invictus",
        favorite: false,
        images: [
          "/images/ambijenti/spavace_sobe/jela/invictus/invictus01.webp",
          "/images/ambijenti/spavace_sobe/jela/invictus/invictus02.webp",
          "/images/ambijenti/spavace_sobe/jela/invictus/invictus03.webp",
          "/images/ambijenti/spavace_sobe/jela/invictus/invictus04.webp",
          "/images/ambijenti/spavace_sobe/jela/invictus/invictus05.webp",
          "/images/ambijenti/spavace_sobe/jela/invictus/invictus06.webp",
          "/images/ambijenti/spavace_sobe/jela/invictus/invictus07.webp",
          "/images/ambijenti/spavace_sobe/jela/invictus/invictus08.webp",
          "/images/ambijenti/spavace_sobe/jela/invictus/invictus09.webp",
        ],
      },
      {
        proizvodjac: "jela",
        img: "piano01",
        naziv: "piano",
        favorite: false,
        images: [
          "/images/ambijenti/spavace_sobe/jela/piano/piano01.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano02.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano03.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano04.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano05.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano06.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano07.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano08.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano09.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano10.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano11.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano12.webp",
          "/images/ambijenti/spavace_sobe/jela/piano/piano13.webp",
        ],
      },
      {
        proizvodjac: "jela",
        img: "tara01",
        naziv: "tara",
        favorite: false,
        images: [
          "/images/ambijenti/spavace_sobe/jela/tara/tara01.webp",
          "/images/ambijenti/spavace_sobe/jela/tara/tara02.webp",
          "/images/ambijenti/spavace_sobe/jela/tara/tara03.webp",
          "/images/ambijenti/spavace_sobe/jela/tara/tara04.webp",
          "/images/ambijenti/spavace_sobe/jela/tara/tara05.webp",
          "/images/ambijenti/spavace_sobe/jela/tara/tara06.webp",
          "/images/ambijenti/spavace_sobe/jela/tara/tara07.webp",
          "/images/ambijenti/spavace_sobe/jela/tara/tara08.webp",
          "/images/ambijenti/spavace_sobe/jela/tara/tara09.webp",
        ],
      },
      {
        proizvodjac: "jela",
        img: "gala01",
        naziv: "gala",
        favorite: false,
        images: [
          "/images/ambijenti/spavace_sobe/jela/gala/gala01.webp",
          "/images/ambijenti/spavace_sobe/jela/gala/gala02.webp",
          "/images/ambijenti/spavace_sobe/jela/gala/gala03.webp",
          "/images/ambijenti/spavace_sobe/jela/gala/gala04.webp",
          "/images/ambijenti/spavace_sobe/jela/gala/gala05.webp",
          "/images/ambijenti/spavace_sobe/jela/gala/gala06.webp",
          "/images/ambijenti/spavace_sobe/jela/gala/gala07.webp",
          "/images/ambijenti/spavace_sobe/jela/gala/gala08.webp",
          "/images/ambijenti/spavace_sobe/jela/gala/gala09.webp",
        ],
      },
      {
        proizvodjac: "jela",
        img: "onyx01",
        naziv: "onyx",
        favorite: false,
        images: [
          "/images/ambijenti/spavace_sobe/jela/onyx/onyx01.webp",
          "/images/ambijenti/spavace_sobe/jela/onyx/onyx02.webp",
          "/images/ambijenti/spavace_sobe/jela/onyx/onyx03.webp",
          "/images/ambijenti/spavace_sobe/jela/onyx/onyx04.webp",
          "/images/ambijenti/spavace_sobe/jela/onyx/onyx05.webp",
        ],
      },
      {
        proizvodjac: "jela",
        img: "evergreen01",
        naziv: "evergreen",
        favorite: false,
        images: [
          "/images/ambijenti/spavace_sobe/jela/evergreen/evergreen01.webp",
          "/images/ambijenti/spavace_sobe/jela/evergreen/evergreen02.webp",
          "/images/ambijenti/spavace_sobe/jela/evergreen/evergreen03.webp",
          "/images/ambijenti/spavace_sobe/jela/evergreen/evergreen04.webp",
        ],
      },

      {
        proizvodjac: "matis",
        img: "asteriks",
        naziv: "asteriks",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "cloud",
        naziv: "cloud",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "hugo",
        naziv: "hugo",
        favorite: false,
      },

      {
        proizvodjac: "matis",
        img: "korleone",
        naziv: "korleone",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "magnum",
        naziv: "magnum",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "titto",
        naziv: "titto",
        favorite: false,
      },
    ],

    // francuski lezajevi

    francuskiLezajevi: [
      {
        proizvodjac: "jela",
        img: "avis",
        naziv: "avis",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "evergreen",
        naziv: "evergreen",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "gala",
        naziv: "gala",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "invictus",
        naziv: "invictus",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "onyx",
        naziv: "onyx",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "piano",
        naziv: "piano",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "tara",
        naziv: "tara",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "asteriks",
        naziv: "asteriks",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "cloud",
        naziv: "cloud",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "hugo",
        naziv: "hugo",
        favorite: false,
      },

      {
        proizvodjac: "matis",
        img: "korleone",
        naziv: "korleone",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "magnum",
        naziv: "magnum",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "titto",
        naziv: "titto",
        favorite: false,
      },

      {
        proizvodjac: "stiljasen",
        img: "lord",
        naziv: "lord",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "lord-2",
        naziv: "lord 2",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "lord-3",
        naziv: "lord 3",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "matrix",
        naziv: "matrix",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "matrix-4",
        naziv: "matrix 4",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "nevada",
        naziv: "nevada",
        favorite: false,
      },

      {
        proizvodjac: "stiljasen",
        img: "stil",
        naziv: "stil",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "stil-4",
        naziv: "stil 4",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "verona-3",
        naziv: "verona 3",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "flex-100x200",
        naziv: "flex 100x200",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "darija-100x200",
        naziv: "darija 100x200",
        favorite: false,
      },

      {
        proizvodjac: "extrasan",
        img: "elit-100x200",
        naziv: "elit 100x200",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "tesla-120x200",
        naziv: "tesla 120x200",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "mona-120x200",
        naziv: "mona 120x200",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "comfort-120x200",
        naziv: "comfort 120x200",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "stil",
        naziv: "stil",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "san",
        naziv: "san",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "rio",
        naziv: "rio",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "premijer",
        naziv: "premijer",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "orion",
        naziv: "orion",
        favorite: false,
      },

      {
        proizvodjac: "extrasan",
        img: "marsej",
        naziv: "marsej",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "kristal",
        naziv: "kristal",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "kocka",
        naziv: "kocka",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "klasik",
        naziv: "klasik",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "king-plus",
        naziv: "king-plus",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "kapri",
        naziv: "kapri",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "jumbo",
        naziv: "jumbo",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "gold",
        naziv: "gold",
        favorite: false,
      },

      {
        proizvodjac: "extrasan",
        img: "cezar",
        naziv: "cezar",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "mille",
        naziv: "mille",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "tesla",
        naziv: "tesla",
        favorite: false,
      },

      {
        proizvodjac: "extrasan",
        img: "lugano",
        naziv: "lugano",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "brisel",
        naziv: "brisel",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "cester",
        naziv: "čester",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "hugo",
        naziv: "hugo",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "lucci",
        naziv: "lucci",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "masimo",
        naziv: "masimo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "cezar",
        naziv: "cezar",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "nelson",
        naziv: "nelson",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "spring",
        naziv: "spring",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "lukas",
        naziv: "lukas",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "luxory",
        naziv: "luxory",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "quatro",
        naziv: "quatro",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "bamboo",
        naziv: "bamboo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "bently",
        naziv: "bently",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "calista",
        naziv: "calista",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "cardif",
        naziv: "cardif",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "carolino",
        naziv: "carolino",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "chester",
        naziv: "chester",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "city",
        naziv: "city",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "del-cubo",
        naziv: "del cubo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "diamond",
        naziv: "diamond",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "diego",
        naziv: "diego",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "enigma",
        naziv: "enigma",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "jumbo-lux",
        naziv: "jumbo lux",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "memory",
        naziv: "memory",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "pariz",
        naziv: "pariz",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "portofino",
        naziv: "portofino",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "rondino",
        naziv: "rondino",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "scarlet",
        naziv: "scarlet",
        favorite: false,
      },
    ],
    drveniKreveti: [
      {
        proizvodjac: "kocic",
        img: "kocic-01",
        naziv: "krevet 01",
        favorite: false,
      },
      {
        proizvodjac: "kocic",
        img: "kocic-02",
        naziv: "krevet 02",
        favorite: false,
      },
      {
        proizvodjac: "kocic",
        img: "kocic-05",
        naziv: "krevet 05",
        favorite: false,
      },
      {
        proizvodjac: "kocic",
        img: "kocic-07",
        naziv: "krevet 07",
        favorite: false,
      },
    ],

    // nocni ormarici
    nocniOrmarici: [
      {
        proizvodjac: "jela",
        img: "avis",
        naziv: "avis",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "evergreen",
        naziv: "evergreen",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "gala",
        naziv: "gala",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "invictus",
        naziv: "invictus",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "onyx",
        naziv: "onyx",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "piano",
        naziv: "piano",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "tara",
        naziv: "tara",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "alfa",
        naziv: "alfa",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "elegance-line",
        naziv: "elegance line",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "kaliopa",
        naziv: "kaliopa",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "magnum",
        naziv: "magnum",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "matis-2f",
        naziv: "matis 2f",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "matis-3f",
        naziv: "matis 3f",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "rustik",
        naziv: "rustik",
        favorite: false,
      },
    ],

    // ormari, plakari, garderoberi
    ormariPlakariGarderoberi: [
      {
        proizvodjac: "matis",
        img: "americki-plakar-ap-230",
        naziv: "američki plakar ap-230",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "americki-plakar-apo-230",
        naziv: "američki plakar apo-230",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "americki-plakar-denver-ap-230",
        naziv: "američki plakar denver ap-230",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "americki-plakar-denver-ap-270",
        naziv: "američki plakar denver ap-270",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "americki-plakar-elegance-ap-230",
        naziv: "američki plakar elegance ap-230",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "americki-plakar-elegance-ap-230",
        naziv: "američki plakar elegance apo-230",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "garderober-fortuna-soft-F2",
        naziv: "garderober fortuna soft F2",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "garderober-fortuna-soft-F3",
        naziv: "garderober fortuna soft F3",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "garderober-fortuna-soft-F75",
        naziv: "garderober fortuna soft F75",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "garderober-fortuna-soft-FU",
        naziv: "garderober fortuna soft FU",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "garderober-kaliopa-270",
        naziv: "garderober kaliopa 270",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "garderober-lara",
        naziv: "garderober lara",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-iva-3k2fo",
        naziv: "ormar iva 3k2fo",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-iva-4k2f",
        naziv: "ormar iva 4k2f",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-iva-4k2fo",
        naziv: "ormar iva 4k2fo",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-iva-k2",
        naziv: "ormar iva k2",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-kaliopa-2V2F",
        naziv: "ormar kaliopa 2V2F",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-kaliopa-3V2F",
        naziv: "ormar kaliopa 3V2F",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-kaliopa-4V3F",
        naziv: "ormar kaliopa 4V3F",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-rustik-3v2f",
        naziv: "ormar rustik 3v2f",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-rustik-4v2fo",
        naziv: "ormar rustik 4v2fo",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "ormar-rustik-4v2f",
        naziv: "ormar rustik 4v2f",
        favorite: false,
      },

      {
        proizvodjac: "jela",
        img: "garderober-evergreen-p2",
        naziv: "garderober evergreen p2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "garderober-evergreen-p3",
        naziv: "garderober evergreen p3",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "garderober-evergreen-p4",
        naziv: "garderober evergreen p4",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-arc-p1",
        naziv: "plakar arc p1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-arc-p2",
        naziv: "plakar arc p2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-arc-p22",
        naziv: "plakar arc p22",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-avis-p2",
        naziv: "plakar avis p2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-avis-p2og",
        naziv: "plakar avis p2og",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-avis-p4",
        naziv: "plakar avis p4",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-avis-p5",
        naziv: "plakar avis p5",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-avis-pk181",
        naziv: "plakar avis pk181",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-avis-pk181og",
        naziv: "plakar avis pk181og",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-avis-pk281",
        naziv: "plakar avis pk281",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-avis-pk281og",
        naziv: "plakar avis pk281og",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-gala-klizni",
        naziv: "plakar gala klizni",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-gala-p22",
        naziv: "plakar gala p22",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-gala-p32",
        naziv: "plakar gala p32",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-invictus-p22",
        naziv: "plakar invictus p22",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-invictus-p32",
        naziv: "plakar invictus p32",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-invictus-p44og",
        naziv: "plakar invictus p44og",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-invictus-p76",
        naziv: "plakar invictus p76",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-klizni-piano",
        naziv: "plakar klizni piano",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-onyx-klizni",
        naziv: "plakar onyx klizni",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-onyx-pk281",
        naziv: "plakar onyx pk281",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-piano-p2",
        naziv: "plakar piano p2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-tara",
        naziv: "plakar tara",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-tara-p3",
        naziv: "plakar tara p3",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "plakar-tara-p6",
        naziv: "plakar tara p6",
        favorite: false,
      },
    ],
  }),
  getters: {},
  actions: {},
});
