import { defineStore } from "pinia";

export const useStoreVisenamenskiNamestaj = defineStore("visenamenski", {
  state: () => ({
    kuhinjskeVitrine: [
      {
        proizvodjac: "djuka",
        img: "01",
        naziv: "jednokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "02",
        naziv: "dvokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "03",
        naziv: "kleopatra",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "04",
        naziv: "dvokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "05",
        naziv: "trokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "06",
        naziv: "jednokrilna serija x",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "07",
        naziv: "dvokrilna serija x",
        favorite: false,
      },
    ],

    vitrine: [
      {
        proizvodjac: "matis",
        img: "01",
        naziv: "barcelona",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "02",
        naziv: "sienna niska",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "03",
        naziv: "sienna visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "04",
        naziv: "porto niska",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "05",
        naziv: "porto visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "06",
        naziv: "treviso visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "07",
        naziv: "linkStyle visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "08",
        naziv: "denver niska",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "09",
        naziv: "denver visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "10",
        naziv: "mediolan",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "11",
        naziv: "staklena visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "12",
        naziv: "staklena niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "01",
        naziv: "avis niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "02",
        naziv: "avis visoka",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "03",
        naziv: "azur",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "04",
        naziv: "brio",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "05",
        naziv: "evergreen staklo",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "06",
        naziv: "evergreen",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "07",
        naziv: "gala-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "08",
        naziv: "gala-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "09",
        naziv: "gala-3",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "10",
        naziv: "gala-4",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "11",
        naziv: "gala-5",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "12",
        naziv: "gala-6",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "13",
        naziv: "f1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "14",
        naziv: "onyx-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "15",
        naziv: "onyx-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "16",
        naziv: "piano-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "17",
        naziv: "piano-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "18",
        naziv: "rio",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "19",
        naziv: "stela-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "20",
        naziv: "stela-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "21",
        naziv: "tara-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "22",
        naziv: "tara-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "23",
        naziv: "tara-3",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "24",
        naziv: "vida",
        favorite: false,
      },
    ],

    kuhinjskeKomode: [
      {
        proizvodjac: "djuka",
        img: "01",
        naziv: "jednokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "02",
        naziv: "dvokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "03",
        naziv: "kleopatra",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "04",
        naziv: "dvokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "05",
        naziv: "trokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "06",
        naziv: "jednokrilna serija x",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "07",
        naziv: "dvokrilna serija x",
        favorite: false,
      },
    ],

    komode: [
      {
        proizvodjac: "jela",
        img: "01",
        naziv: "arc",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "02",
        naziv: "arc d7",
        favorite: false,
      },

      {
        proizvodjac: "jela",
        img: "03",
        naziv: "avis dvokrilna",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "04",
        naziv: "avis trokrilna",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "05",
        naziv: "avis fioke",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "06",
        naziv: "brio niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "07",
        naziv: "brio visoka",
        favorite: false,
      },

      {
        proizvodjac: "jela",
        img: "09",
        naziv: "evergreen niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "10",
        naziv: "evergreen visoka",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "11",
        naziv: "piano niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "12",
        naziv: "piano visoka",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "13",
        naziv: "tara niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "14",
        naziv: "tara fioke",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "15",
        naziv: "onyx jastuk",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "16",
        naziv: "onyx niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "17",
        naziv: "onyx visoka",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "18",
        naziv: "onyx fioke",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "19",
        naziv: "gala",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "20",
        naziv: "nica niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "21",
        naziv: "nica visoka",
        favorite: false,
      },

      {
        proizvodjac: "jela",
        img: "23",
        naziv: "stela jastuk",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "24",
        naziv: "stela",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "25",
        naziv: "vida niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "26",
        naziv: "vida visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "01",
        naziv: "porto",
        favorite: false,
      },

      {
        proizvodjac: "matis",
        img: "01",
        naziv: "porto",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "03",
        naziv: "elegance",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "04",
        naziv: "rustic",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "05",
        naziv: "sienna",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "06",
        naziv: "trevisa",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "07",
        naziv: "roma",
        favorite: false,
      },

      {
        proizvodjac: "matis",
        img: "09",
        naziv: "roma 150",
        favorite: false,
      },

      {
        proizvodjac: "matis",
        img: "11",
        naziv: "denver",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "12",
        naziv: "contempo",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "13",
        naziv: "contempo",
        favorite: false,
      },

      {
        proizvodjac: "attrium",
        img: "01",
        naziv: "ela",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "02",
        naziv: "lara",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "03",
        naziv: "milica",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "04",
        naziv: "lisa",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "05",
        naziv: "meri",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "06",
        naziv: "helena",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "07",
        naziv: "quattro",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "08",
        naziv: "trif",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "09",
        naziv: "grand",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "10",
        naziv: "mila",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "11",
        naziv: "nica",
        favorite: false,
      },

      {
        proizvodjac: "attrium",
        img: "13",
        naziv: "tria",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "14",
        naziv: "loka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "01",
        naziv: "jednokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "02",
        naziv: "dvokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "03",
        naziv: "kleopatra",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "04",
        naziv: "dvokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "05",
        naziv: "trokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "06",
        naziv: "jednokrilna serija x",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "07",
        naziv: "dvokrilna serija x",
        favorite: false,
      },
    ],
    radneStolice: [
      {
        proizvodjac: "matis",
        img: "a5-d",
        naziv: "a5-d",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "a15-mb",
        naziv: "a15-mb",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "a15-mrb",
        naziv: "a15-mrb",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "alfa",
        naziv: "alfa",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "bandra",
        naziv: "bandra",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "bella",
        naziv: "bella",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "disco",
        naziv: "disco",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "eden",
        naziv: "eden",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "eden-31",
        naziv: "eden 31",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "joker",
        naziv: "joker",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "kidy",
        naziv: "kidy",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "kingston-b",
        naziv: "kingston b",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "klara",
        naziv: "klara",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "lena",
        naziv: "lena",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "light-b",
        naziv: "light b",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "lol",
        naziv: "lol",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "mina",
        naziv: "mina",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "office",
        naziv: "office",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "patrik",
        naziv: "patrik",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "pol",
        naziv: "pol",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "Radna-fotelja-7801",
        naziv: "Radna fotelja 7801",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "smart",
        naziv: "smart",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "standard",
        naziv: "standard",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "torium",
        naziv: "torium",
        favorite: false,
      },
    ],
    // lezajevi
    lezajevi: [
      {
        proizvodjac: "numanovic",
        img: "01",
        naziv: "bologna-lux",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "02",
        naziv: "fabia",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "03",
        naziv: "toledo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "04",
        naziv: "tomy",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "05",
        naziv: "lima",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "06",
        naziv: "castillo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "07",
        naziv: "rivoli",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "08",
        naziv: "maldivi",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "09",
        naziv: "grof",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "10",
        naziv: "grofmena",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "11",
        naziv: "mistik",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "12",
        naziv: "alegro",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "13",
        naziv: "lido",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "14",
        naziv: "new york",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "15",
        naziv: "boni",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "16",
        naziv: "harmony",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "17",
        naziv: "santos",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "18",
        naziv: "manila",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "19",
        naziv: "hanioti",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "20",
        naziv: "still line",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "21",
        naziv: "massimo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "22",
        naziv: "manchester",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "23",
        naziv: "conga",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "24",
        naziv: "bambus",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "01",
        naziv: "bolero",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "02",
        naziv: "nobel",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "03",
        naziv: "piano",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "04",
        naziv: "romansa",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "05",
        naziv: "salle-plus",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "06",
        naziv: "vento",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "07",
        naziv: "tivoli",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "08",
        naziv: "magnum",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "09",
        naziv: "toledo",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "10",
        naziv: "viva",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "11",
        naziv: "armani",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "12",
        naziv: "harmoni",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "13",
      //   naziv: "amor",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "extrasan",
      //   img: "14",
      //   naziv: "tango",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "extrasan",
      //   img: "15",
      //   naziv: "junior",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "16",
        naziv: "bosfor",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "17",
        naziv: "klasik",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "18",
        naziv: "klasik-lux",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "19",
        naziv: "madrid",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "20",
        naziv: "milano",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "21",
        naziv: "salle",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "22",
        naziv: "delta",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "23",
        naziv: "fabia",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "24",
        naziv: "nica",
        favorite: false,
      },

      {
        proizvodjac: "stiljasen",
        img: "01",
        naziv: "alma",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "02",
        naziv: "relax",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "03",
        naziv: "idea",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "04",
        naziv: "leo",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "05",
        naziv: "relax-lux",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "06",
        naziv: "porto",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "07",
        naziv: "amore",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "08",
        naziv: "uno",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "09",
        naziv: "sundjer bob",
        favorite: false,
      },
    ],
  }),
  getters: {},
  actions: {},
});
