import { defineStore } from "pinia";

export const useStoreDnevneSobe = defineStore("dnevneSobe", {
  state: () => ({
    // ambijenti
    dnevneSobe: [
      {
        proizvodjac: "jela",
        img: "01",
        naziv: "avis",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/avis/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/avis/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/avis/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/avis/04.jpg",
          "/images/ambijenti/dnevne_sobe/jela/avis/05.jpg",
          "/images/ambijenti/dnevne_sobe/jela/avis/06.jpg",
        ],
      },
      {
        proizvodjac: "jela",
        img: "02",
        naziv: "tara",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/tara/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/tara/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/tara/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/tara/04.jpg",
          "/images/ambijenti/dnevne_sobe/jela/tara/05.jpg",
          "/images/ambijenti/dnevne_sobe/jela/tara/06.jpg",
          "/images/ambijenti/dnevne_sobe/jela/tara/07.jpg",
          "/images/ambijenti/dnevne_sobe/jela/tara/08.jpg",
        ],
      },
      {
        proizvodjac: "jela",
        img: "03",
        naziv: "gala",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/gala/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/gala/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/gala/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/gala/04.jpg",
          "/images/ambijenti/dnevne_sobe/jela/gala/05.jpg",
        ],
      },
      {
        proizvodjac: "jela",
        img: "04",
        naziv: "piano",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/piano/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/04.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/05.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/06.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/07.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/08.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/09.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/10.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/11.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/12.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/13.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/14.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/15.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/16.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/17.jpg",
          "/images/ambijenti/dnevne_sobe/jela/piano/18.jpg",
        ],
      },
      {
        proizvodjac: "jela",
        img: "05",
        naziv: "vida",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/vida/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/vida/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/vida/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/vida/04.jpg",
          "/images/ambijenti/dnevne_sobe/jela/vida/05.jpg",
        ],
      },
      {
        proizvodjac: "jela",
        img: "06",
        naziv: "brio",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/brio/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/brio/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/brio/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/brio/04.jpg",
        ],
      },
      {
        proizvodjac: "jela",
        img: "07",
        naziv: "onyx",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/onyx/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/onyx/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/onyx/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/onyx/04.jpg",
          "/images/ambijenti/dnevne_sobe/jela/onyx/05.jpg",
          "/images/ambijenti/dnevne_sobe/jela/onyx/06.jpg",
          "/images/ambijenti/dnevne_sobe/jela/onyx/07.jpg",
        ],
      },
      {
        proizvodjac: "jela",
        img: "08",
        naziv: "stela",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/stela/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/stela/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/stela/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/stela/04.jpg",
          "/images/ambijenti/dnevne_sobe/jela/stela/05.jpg",
        ],
      },
      {
        proizvodjac: "jela",
        img: "09",
        naziv: "nica",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/nica/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/nica/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/nica/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/nica/04.jpg",
          "/images/ambijenti/dnevne_sobe/jela/nica/05.jpg",
          "/images/ambijenti/dnevne_sobe/jela/nica/06.jpg",
          "/images/ambijenti/dnevne_sobe/jela/nica/07.jpg",
          "/images/ambijenti/dnevne_sobe/jela/nica/08.jpg",
        ],
      },
      {
        proizvodjac: "jela",
        img: "10",
        naziv: "evergreen",
        favorite: false,
        images: [
          "/images/ambijenti/dnevne_sobe/jela/evergreen/01.jpg",
          "/images/ambijenti/dnevne_sobe/jela/evergreen/02.jpg",
          "/images/ambijenti/dnevne_sobe/jela/evergreen/03.jpg",
          "/images/ambijenti/dnevne_sobe/jela/evergreen/04.jpg",
        ],
      },
      {
        proizvodjac: "matis",
        img: "01",
        naziv: "barcelona",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "02",
        naziv: "contempo",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "03",
        naziv: "rustik",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "serija-x",
        naziv: "serija-x",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "s-7",
        naziv: "s-7",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "s-4_a",
        naziv: "s-4/a",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "kleopatra",
        naziv: "kleopatra",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "linea",
        naziv: "linea",
        favorite: false,
      },
    ],

    // klub stolovi
    klubStolovi: [
      {
        proizvodjac: "jela",
        img: "01",
        naziv: "brio",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "02",
        naziv: "vida",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "03",
        naziv: "gala",
        favorite: false,
      },

      {
        proizvodjac: "jela",
        img: "05",
        naziv: "avis",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "06",
        naziv: "piano",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "07",
        naziv: "nica",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "08",
        naziv: "evergreen",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "09",
        naziv: "stela",
        favorite: false,
      },
      // {
      //   proizvodjac: "jela",
      //   img: "10",
      //   naziv: "joy",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "jela",
      //   img: "11",
      //   naziv: "kiki",
      //   favorite: false,
      // },
      {
        proizvodjac: "jela",
        img: "12",
        naziv: "onyx",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "13",
        naziv: "tara",
        favorite: false,
      },
      // {
      //   proizvodjac: "matis",
      //   img: "01",
      //   naziv: "marco",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "02",
      //   naziv: "poprad",
      //   favorite: false,
      // },
      {
        proizvodjac: "matis",
        img: "03",
        naziv: "valencia",
        favorite: false,
      },
      // {
      //   proizvodjac: "matis",
      //   img: "04",
      //   naziv: "lagos",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "05",
      //   naziv: "smocky",
      //   favorite: false,
      // },
      {
        proizvodjac: "matis",
        img: "06",
        naziv: "saturn",
        favorite: false,
      },

      // {
      //   proizvodjac: "matis",
      //   img: "08",
      //   naziv: "pensea",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "09",
      //   naziv: "leon",
      //   favorite: false,
      // },
      {
        proizvodjac: "matis",
        img: "10",
        naziv: "porto",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "11",
        naziv: "delta",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "12",
        naziv: "leo",
        favorite: false,
      },
      // {
      //   proizvodjac: "matis",
      //   img: "13",
      //   naziv: "grom",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "14",
      //   naziv: "sevilla",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "15",
      //   naziv: "intro",
      //   favorite: false,
      // },
      {
        proizvodjac: "attrium",
        img: "01",
        naziv: "54",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "02",
        naziv: "attrium",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "03",
        naziv: "trio",
        favorite: false,
      },
      // {
      //   proizvodjac: "attrium",
      //   img: "04",
      //   naziv: "laki",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "attrium",
      //   img: "05",
      //   naziv: "laki-5",
      //   favorite: false,
      // },
      {
        proizvodjac: "attrium",
        img: "06",
        naziv: "lela",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "07",
        naziv: "luna",
        favorite: false,
      },
      // {
      //   proizvodjac: "attrium",
      //   img: "08",
      //   naziv: "evn",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "attrium",
      //   img: "09",
      //   naziv: "tina",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "attrium",
      //   img: "10",
      //   naziv: "nera",
      //   favorite: false,
      // },
    ],

    // ugaone garniture
    ugaoneGarniture: [
      {
        proizvodjac: "matis",
        img: "04",
        naziv: "havana",
        favorite: false,
      },

      {
        proizvodjac: "matis",
        img: "09",
        naziv: "casablanca",
        favorite: false,
      },

      {
        proizvodjac: "matis",
        img: "11",
        naziv: "diego",
        favorite: false,
      },

      {
        proizvodjac: "matis",
        img: "15",
        naziv: "queen",
        favorite: false,
      },

      {
        proizvodjac: "numanovic",
        img: "01",
        naziv: "perfekta",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "02",
        naziv: "lota",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "03",
        naziv: "bono",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "04",
        naziv: "alegro",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "05",
        naziv: "avangard",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "06",
        naziv: "barbados",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "07",
        naziv: "bologna",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "08",
        naziv: "carla",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "09",
        naziv: "carmen",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "10",
        naziv: "contesa",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "11",
        naziv: "cuba",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "12",
        naziv: "emerald",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "13",
        naziv: "florya",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "14",
        naziv: "fuego",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "15",
        naziv: "galaxi",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "16",
        naziv: "havana",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "17",
        naziv: "helena",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "18",
        naziv: "lana",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "19",
        naziv: "lela",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "20",
        naziv: "lina",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "21",
        naziv: "mancester",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "22",
        naziv: "manila",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "23",
        naziv: "melany",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "24",
        naziv: "montana",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "25",
        naziv: "napoli",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "26",
        naziv: "ontario",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "27",
        naziv: "perfekta-lux",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "28",
        naziv: "princeza",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "29",
        naziv: "rebeka",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "30",
        naziv: "romana",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "31",
        naziv: "tango",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "32",
        naziv: "teodora",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "33",
        naziv: "toledo",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "01",
        naziv: "arizona",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "02",
        naziv: "brisel",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "03",
        naziv: "cuba",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "04",
        naziv: "darija",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "05",
        naziv: "domino",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "06",
      //   naziv: "ena",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "extrasan",
      //   img: "07",
      //   naziv: "exklusiv",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "08",
        naziv: "gala",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "09",
        naziv: "kristal",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "10",
        naziv: "london",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "11",
        naziv: "milano-lux",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "12",
        naziv: "milano",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "13",
        naziv: "piano",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "14",
      //   naziv: "sila",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "extrasan",
      //   img: "15",
      //   naziv: "tajland",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "16",
        naziv: "venecija",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "17",
        naziv: "vento",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "18",
        naziv: "zara",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "19",
        naziv: "bombaj-lux",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "20",
      //   naziv: "čester",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "21",
        naziv: "comforto",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "22",
        naziv: "domino-lux",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "23",
        naziv: "dubai",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "24",
        naziv: "harmoni",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "25",
        naziv: "havana",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "26",
        naziv: "hilton",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "27",
        naziv: "hurem",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "28",
      //   naziv: "lora",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "29",
        naziv: "magnum",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "30",
        naziv: "maja",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "31",
        naziv: "mona",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "32",
        naziv: "nela",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "33",
        naziv: "nica",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "34",
        naziv: "nica-mini",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "35",
        naziv: "nobel",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "36",
        naziv: "polaris",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "37",
        naziv: "polo",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "38",
        naziv: "toledo",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "39",
        naziv: "trend",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "40",
        naziv: "venus",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "41",
        naziv: "viva",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "42",
        naziv: "viva-mini ",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "01",
        naziv: "dalia",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "02",
        naziv: "malta",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "03",
        naziv: "modena",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "04",
        naziv: "linea",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "05",
        naziv: "linea-2",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "06",
        naziv: "linea-3",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "07",
        naziv: "linea-4",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "08",
        naziv: "dona-2",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "09",
        naziv: "dona-3",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "10",
        naziv: "sara",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "11",
        naziv: "sara-2",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "12",
        naziv: "sara-3",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "13",
        naziv: "sara-mini",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "14",
        naziv: "helena",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "15",
        naziv: "lorena",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "16",
        naziv: "monako",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "17",
        naziv: "samba",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "18",
        naziv: "samba-2",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "19",
        naziv: "samba-4",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "20",
        naziv: "savana",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "21",
        naziv: "gracia",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "22",
        naziv: "tea",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "23",
        naziv: "zafira",
        favorite: false,
      },
    ],

    // TDF garniture
    tdfGarniture: [
      {
        proizvodjac: "matis",
        img: "01",
        naziv: "trosed living",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "02",
        naziv: "dvosed living",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "03",
        naziv: "fotelja living",
        favorite: false,
      },
      // {
      //   proizvodjac: "matis",
      //   img: "04",
      //   naziv: "trosed polaris",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "05",
      //   naziv: "dvosed polaris",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "06",
      //   naziv: "fotelja polaris",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "07",
      //   naziv: "trosed dalas",
      //   favorite: false,
      // },

      // {
      //   proizvodjac: "matis",
      //   img: "08",
      //   naziv: "dvosed dalas",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "09",
      //   naziv: "fotelja dalas",
      //   favorite: false,
      // },
      {
        proizvodjac: "matis",
        img: "10",
        naziv: "trosed boss",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "11",
        naziv: "dvosed boss",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "12",
        naziv: "fotelja boss",
        favorite: false,
      },

      // {
      //   proizvodjac: "matis",
      //   img: "13",
      //   naziv: "trosed malfas",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "14",
      //   naziv: "dvosed malfas",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "15",
      //   naziv: "fotelja malfas",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "16",
      //   naziv: "trosed dora",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "17",
      //   naziv: "dvosed dora",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "18",
      //   naziv: "fotelja dora",
      //   favorite: false,
      // },

      // {
      //   proizvodjac: "matis",
      //   img: "19",
      //   naziv: "dvosed barbados",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "20",
      //   naziv: "fotelja barbados",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "21",
      //   naziv: "dvosed emporio",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "22",
      //   naziv: "fotelja emporio",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "23",
      //   naziv: "dvosed eos",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "24",
      //   naziv: "trosed astra",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "25",
      //   naziv: "trosed capri",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "26",
      //   naziv: "trosed diamond",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "27",
      //   naziv: "trosed london",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "28",
      //   naziv: "trosed atina",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "29",
      //   naziv: "trosed kimi",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "30",
      //   naziv: "trosed best",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "31",
      //   naziv: "trosed planet",
      //   favorite: false,
      // },

      // {
      //   proizvodjac: "matis",
      //   img: "35",
      //   naziv: "trosed sa električnim mehanizmom",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "36",
      //   naziv: "fotelja armani",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "37",
      //   naziv: "fotelja charleston",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "38",
      //   naziv: "fotelja klara",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "39",
      //   naziv: "fotelja nika",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "12",
      //   naziv: "fotelja boss",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "40",
      //   naziv: "fotelja queen",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "41",
      //   naziv: "fotelja gracia",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "42",
      //   naziv: "fotelja ida",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "43",
      //   naziv: "fotelja vanilica",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "44",
      //   naziv: "fotelja wish",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "45",
      //   naziv: "fotelja nino",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "46",
      //   naziv: "fotelja rimini",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "47",
      //   naziv: "fotelja vento",
      //   favorite: false,
      // },
      {
        proizvodjac: "numanovic",
        img: "01",
        naziv: "florya",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "02",
        naziv: "capella",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "03",
        naziv: "bergamo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "04",
        naziv: "moica-lux",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "05",
        naziv: "atalanta",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "06",
        naziv: "linea",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "07",
        naziv: "adria",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "08",
        naziv: "agata-lux",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "09",
        naziv: "atlas",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "10",
        naziv: "fuego",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "11",
        naziv: "belinda",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "12",
        naziv: "tango",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "13",
        naziv: "napoli",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "14",
        naziv: "montana",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "15",
        naziv: "domino",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "01",
      //   naziv: "bosfor",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "02",
        naziv: "darija",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "03",
      //   naziv: "lotus",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "extrasan",
      //   img: "04",
      //   naziv: "majami",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "05",
        naziv: "milano",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "06",
      //   naziv: "nobel",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "extrasan",
      //   img: "07",
      //   naziv: "polo",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "08",
        naziv: "romansa",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "09",
        naziv: "arizona",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "10",
        naziv: "čester",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "11",
        naziv: "comfort",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "12",
        naziv: "havana",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "13",
        naziv: "hilton",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "14",
      //   naziv: "kristal",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "15",
        naziv: "luna",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "16",
      //   naziv: "odesa",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "17",
        naziv: "polaris",
        favorite: false,
      },
      // {
      //   proizvodjac: "extrasan",
      //   img: "18",
      //   naziv: "stil",
      //   favorite: false,
      // },
      {
        proizvodjac: "extrasan",
        img: "19",
        naziv: "venecija",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "20",
        naziv: "hurem",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "21",
        naziv: "domino",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "22",
        naziv: "harmoni",
        favorite: false,
      },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "01",
      //   naziv: "boston",
      //   favorite: false,
      // },
      {
        proizvodjac: "stiljasen",
        img: "02",
        naziv: "havana",
        favorite: false,
      },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "03",
      //   naziv: "havana-2",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "04",
      //   naziv: "malta",
      //   favorite: false,
      // },
      {
        proizvodjac: "stiljasen",
        img: "05",
        naziv: "dubai",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "06",
        naziv: "grand",
        favorite: false,
      },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "07",
      //   naziv: "dona",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "08",
      //   naziv: "dona-2",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "09",
      //   naziv: "penelopa",
      //   favorite: false,
      // },

      // {
      //   proizvodjac: "stiljasen",
      //   img: "10",
      //   naziv: "iva",
      //   favorite: false,
      // },
      {
        proizvodjac: "stiljasen",
        img: "11",
        naziv: "bosfor",
        favorite: false,
      },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "12",
      //   naziv: "atina",
      //   favorite: false,
      // },
      {
        proizvodjac: "stiljasen",
        img: "13",
        naziv: "linea",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "14",
        naziv: "exclusive",
        favorite: false,
      },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "15",
      //   naziv: "helena",
      //   favorite: false,
      // },
      {
        proizvodjac: "stiljasen",
        img: "16",
        naziv: "london",
        favorite: false,
      },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "17",
      //   naziv: "milano",
      //   favorite: false,
      // },
      {
        proizvodjac: "stiljasen",
        img: "18",
        naziv: "royal",
        favorite: false,
      },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "19",
      //   naziv: "safari",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "stiljasen",
      //   img: "20",
      //   naziv: "maroko",
      //   favorite: false,
      // },
      {
        proizvodjac: "stiljasen",
        img: "21",
        naziv: "sena",
        favorite: false,
      },
    ],

    // fotelje i taburei
    foteljeItaburei: [
      {
        proizvodjac: "matis",
        img: "43",
        naziv: "fotelja vanilica",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "12",
        naziv: "fotelja boss",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "40",
        naziv: "fotelja queen",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "41",
        naziv: "fotelja gracia",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "03",
        naziv: "fotelja living",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "04",
        naziv: "fotelja perla",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "01",
        naziv: "venecija",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "02",
        naziv: "univerzal",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "03",
        naziv: "armani",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "04",
        naziv: "smart",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "05",
        naziv: "smart-plus",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "06",
        naziv: "fabia",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "07",
        naziv: "potkovica",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "08",
        naziv: "matrix",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "09",
        naziv: "tabure maldivi",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "10",
        naziv: "sila",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "11",
        naziv: "venecija",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "01",
        naziv: "snow",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "02",
        naziv: "cloud",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "03",
        naziv: "lisbow",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "04",
        naziv: "retro",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "05",
        naziv: "classic",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "06",
        naziv: "swing",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "07",
        naziv: "camel",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "08",
        naziv: "pepito",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "09",
        naziv: "mimoza",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "10",
        naziv: "ada",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "11",
        naziv: "4you",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "12",
        naziv: "fotelja v",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "13",
        naziv: "lima",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "14",
        naziv: "manchester",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "15",
        naziv: "new-york",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "16",
        naziv: "lord",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "17",
        naziv: "mona",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "18",
        naziv: "glamur",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "19",
        naziv: "bologna",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "20",
        naziv: "castillo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "21",
        naziv: "manchester-piano",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "22",
        naziv: "relax",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "23",
        naziv: "trendy",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "24",
        naziv: "velvet",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "25",
        naziv: "pouf",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "26",
        naziv: "storage",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "27",
        naziv: "tresure",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "28",
        naziv: "barbados",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "29",
        naziv: "castillo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "30",
        naziv: "cesterfild",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "31",
        naziv: "emerald",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "32",
        naziv: "stil-line",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "33",
        naziv: "melany",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "34",
        naziv: "venecija",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "35",
        naziv: "stil-line malo",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "36",
        naziv: "lorena",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "37",
        naziv: "stand",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "38",
        naziv: "stool",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "39",
        naziv: "braid",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "40",
        naziv: "frog",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "41",
        naziv: "lion",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "42",
        naziv: "kanabe",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "43",
        naziv: "drawer",
        favorite: false,
      },
    ],

    // kaucevi
    kaucevi: [
      {
        proizvodjac: "extrasan",
        img: "02",
        naziv: "elit",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "03",
        naziv: "romansa",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "04",
        naziv: "verona",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "05",
        naziv: "nobel",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "06",
        naziv: "orion",
        favorite: false,
      },
      {
        proizvodjac: "extrasan",
        img: "07",
        naziv: "elegant",
        favorite: false,
      },

      {
        proizvodjac: "extrasan",
        img: "09",
        naziv: "klasik",
        favorite: false,
      },

      {
        proizvodjac: "extrasan",
        img: "11",
        naziv: "piano",
        favorite: false,
      },

      {
        proizvodjac: "numanovic",
        img: "01",
        naziv: "gordon",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "02",
        naziv: "alfa",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "03",
        naziv: "rio",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "04",
        naziv: "sara",
        favorite: false,
      },
      {
        proizvodjac: "numanovic",
        img: "05",
        naziv: "venera",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "01",
        naziv: "bolero",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "02",
        naziv: "boston",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "03",
        naziv: "jasen",
        favorite: false,
      },
      {
        proizvodjac: "stiljasen",
        img: "04",
        naziv: "bravo",
        favorite: false,
      },
    ],

    // tv komode
    tvKomode: [
      {
        proizvodjac: "attrium",
        img: "bilja",
        naziv: "bilja",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "ika",
        naziv: "ika",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "luna",
        naziv: "luna",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "mina",
        naziv: "mina",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "retro",
        naziv: "retro",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "zoka",
        naziv: "zoka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "linea",
        naziv: "linea",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "kleopatra-trokrilna",
        naziv: "kleopatra-trokrilna",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "kleopatra",
        naziv: "kleopatra",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "s-4-a",
        naziv: "s4/a",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "serija-s7",
        naziv: "serija-s7",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "arc-1",
        naziv: "arc-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "arc-2",
        naziv: "arc-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "arc-3",
        naziv: "arc-3",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "arc-4",
        naziv: "arc-4",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "avis-1",
        naziv: "avis-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "brio-1",
        naziv: "brio-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "evergreen-1",
        naziv: "evergreen-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "gala-1",
        naziv: "gala-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "gala-2",
        naziv: "gala-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "nica-1",
        naziv: "nica-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "onyx-1",
        naziv: "onyx-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "piano-1",
        naziv: "piano-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "piano-2",
        naziv: "piano-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "sky-1",
        naziv: "sky-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "sky-2",
        naziv: "sky-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "sky-3",
        naziv: "sky-3",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "stela-1",
        naziv: "stela-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "tara-1",
        naziv: "tara-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "tara-2",
        naziv: "tara-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "vida-1",
        naziv: "vida-1",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "barcelona",
        naziv: "barcelona",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "contempo",
        naziv: "contempo",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "denver",
        naziv: "denver",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "napoli",
        naziv: "napoli",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "porto",
        naziv: "porto",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "rustik",
        naziv: "rustik",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "sienna",
        naziv: "sienna",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "treviso",
        naziv: "treviso",
        favorite: false,
      },
    ],
  }),
  getters: {},
  actions: {},
});
