import { defineStore } from "pinia";

export const useStoreVisenamenskiNamestaj = defineStore("visenamenski", {
  state: () => ({
    kuhinjskeVitrine: [
      {
        proizvodjac: "djuka",
        img: "01",
        naziv: "jednokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "02",
        naziv: "dvokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "03",
        naziv: "kleopatra",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "04",
        naziv: "dvokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "05",
        naziv: "trokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "06",
        naziv: "jednokrilna serija x",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "07",
        naziv: "dvokrilna serija x",
        favorite: false,
      },
    ],

    vitrine: [
      {
        proizvodjac: "matis",
        img: "01",
        naziv: "barcelona",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "02",
        naziv: "sienna niska",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "03",
        naziv: "sienna visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "04",
        naziv: "porto niska",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "05",
        naziv: "porto visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "06",
        naziv: "treviso visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "07",
        naziv: "linkStyle visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "08",
        naziv: "denver niska",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "09",
        naziv: "denver visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "10",
        naziv: "mediolan",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "11",
        naziv: "staklena visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "12",
        naziv: "staklena niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "01",
        naziv: "avis niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "02",
        naziv: "avis visoka",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "03",
        naziv: "azur",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "04",
        naziv: "brio",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "05",
        naziv: "evergreen staklo",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "06",
        naziv: "evergreen",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "07",
        naziv: "gala-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "08",
        naziv: "gala-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "09",
        naziv: "gala-3",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "10",
        naziv: "gala-4",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "11",
        naziv: "gala-5",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "12",
        naziv: "gala-6",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "13",
        naziv: "f1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "14",
        naziv: "onyx-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "15",
        naziv: "onyx-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "16",
        naziv: "piano-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "17",
        naziv: "piano-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "18",
        naziv: "rio",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "19",
        naziv: "stela-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "20",
        naziv: "stela-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "21",
        naziv: "tara-1",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "22",
        naziv: "tara-2",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "23",
        naziv: "tara-3",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "24",
        naziv: "vida",
        favorite: false,
      },
    ],

    kuhinjskeKomode: [
      {
        proizvodjac: "djuka",
        img: "01",
        naziv: "jednokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "02",
        naziv: "dvokrilna biblioteka",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "03",
        naziv: "kleopatra",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "04",
        naziv: "dvokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "05",
        naziv: "trokrilna nadogradnja",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "06",
        naziv: "jednokrilna serija x",
        favorite: false,
      },
      {
        proizvodjac: "djuka",
        img: "07",
        naziv: "dvokrilna serija x",
        favorite: false,
      },
    ],

    komode: [
      {
        proizvodjac: "jela",
        img: "01",
        naziv: "arc",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "02",
        naziv: "arc d7",
        favorite: false,
      },

      {
        proizvodjac: "jela",
        img: "03",
        naziv: "avis dvokrilna",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "04",
        naziv: "avis trokrilna",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "05",
        naziv: "avis fioke",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "06",
        naziv: "brio niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "07",
        naziv: "brio visoka",
        favorite: false,
      },

      {
        proizvodjac: "jela",
        img: "09",
        naziv: "evergreen niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "10",
        naziv: "evergreen visoka",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "11",
        naziv: "piano niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "12",
        naziv: "piano visoka",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "13",
        naziv: "tara niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "14",
        naziv: "tara fioke",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "15",
        naziv: "onyx jastuk",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "16",
        naziv: "onyx niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "17",
        naziv: "onyx visoka",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "18",
        naziv: "onyx fioke",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "19",
        naziv: "gala",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "20",
        naziv: "nica niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "21",
        naziv: "nica visoka",
        favorite: false,
      },

      {
        proizvodjac: "jela",
        img: "23",
        naziv: "stela jastuk",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "24",
        naziv: "stela",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "25",
        naziv: "vida niska",
        favorite: false,
      },
      {
        proizvodjac: "jela",
        img: "26",
        naziv: "vida visoka",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "01",
        naziv: "porto",
        favorite: false,
      },
      // {
      //   proizvodjac: "matis",
      //   img: "02",
      //   naziv: "linkStyle",
      //   favorite: false,
      // },
      {
        proizvodjac: "matis",
        img: "01",
        naziv: "porto",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "03",
        naziv: "elegance",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "04",
        naziv: "rustic",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "05",
        naziv: "sienna",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "06",
        naziv: "trevisa",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "07",
        naziv: "roma",
        favorite: false,
      },
      // {
      //   proizvodjac: "matis",
      //   img: "08",
      //   naziv: "roma ugaona",
      //   favorite: false,
      // },
      {
        proizvodjac: "matis",
        img: "09",
        naziv: "roma 150",
        favorite: false,
      },
      // {
      //   proizvodjac: "matis",
      //   img: "10",
      //   naziv: "mediolan",
      //   favorite: false,
      // },
      {
        proizvodjac: "matis",
        img: "11",
        naziv: "denver",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "12",
        naziv: "contempo",
        favorite: false,
      },
      {
        proizvodjac: "matis",
        img: "13",
        naziv: "contempo",
        favorite: false,
      },

      // {
      //   proizvodjac: "matis",
      //   img: "14",
      //   naziv: "grand",
      //   favorite: false,
      // },

      // {
      //   proizvodjac: "matis",
      //   img: "15",
      //   naziv: "kairo",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "16",
      //   naziv: "leon",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "matis",
      //   img: "17",
      //   naziv: "orion",
      //   favorite: false,
      // },
      {
        proizvodjac: "attrium",
        img: "01",
        naziv: "ela",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "02",
        naziv: "lara",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "03",
        naziv: "milica",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "04",
        naziv: "lisa",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "05",
        naziv: "meri",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "06",
        naziv: "helena",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "07",
        naziv: "quattro",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "08",
        naziv: "trif",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "09",
        naziv: "grand",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "10",
        naziv: "mila",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "11",
        naziv: "nica",
        favorite: false,
      },
      // {
      //   proizvodjac: "attrium",
      //   img: "12",
      //   naziv: "violeta",
      //   favorite: false,
      // },
      {
        proizvodjac: "attrium",
        img: "13",
        naziv: "tria",
        favorite: false,
      },
      {
        proizvodjac: "attrium",
        img: "14",
        naziv: "loka",
        favorite: false,
      },
      // {
      //   proizvodjac: "attrium",
      //   img: "15",
      //   naziv: "tatijana",
      //   favorite: false,
      // },
      // {
      //   proizvodjac: "attrium",
      //   img: "16",
      //   naziv: "irisa",
      //   favorite: false,
      // },
    ],
  }),
  getters: {},
  actions: {},
});
